### ISSUE TITLE
Проблема с транзакциями

### ISSUE THREAD

**Issue by Hunternnm** [cycle/orm#117]
Через некоторое время работы воркера при попытке записать что-то в БД с использованием транзакции начинает появляться ошибка:
```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT SVP-3 does not exist in /app/vendor/spiral/database/src/Driver/Driver.php:471
Stack trace:
#0 /app/vendor/spiral/database/src/Driver/Driver.php(471): PDOStatement->execute()
#1 /app/vendor/spiral/database/src/Driver/Driver.php(323): Spiral\Database\Driver\Driver->statement('RELEASE SAVEPOI...', Array)
#2 /app/vendor/spiral/database/src/Driver/Driver.php(634): Spiral\Database\Driver\Driver->execute('RELEASE SAVEPOI...')
#3 /app/vendor/spiral/database/src/Driver/Driver.php(412): Spiral\Database\Driver\Driver->releaseSavepoint(-3)
#4 /app/vendor/cycle/orm/src/Transaction/Runner.php(70): Spiral\Database\Driver\Driver->commitTransaction()
#5 /app/vendor/cycle/orm/src/Transaction.php(137): Cycle\ORM\Transaction\Runner->complete()
#6 /app/app/src/Repository/SecretAuthKeyRepository.php(42): Cycle\ORM\Transaction->run()
```
Ошибка зависит от воркера RR, т.е. проблема не на стороне БД. С каждым следующим запросом номер SVP увеличивается на единицу. Предварительно проблема в дисконнекте воркера от MySQL и последующем реконнекте. Потенциально проблемное место:
vendor/spiral/database/src/Driver/Driver.php:353
```php
public function beginTransaction(string $isolationLevel = null): bool
{
    $this->transactionLevel++;
    if ($this->transactionLevel === 1) {
        if ($isolationLevel !== null) {
            $this->setIsolationLevel($isolationLevel);
        }
        if ($this->logger !== null) {
            $this->logger->info('Begin transaction');
        }
        try {
            return $this->getPDO()->beginTransaction();
        } catch (Throwable  $e) {
            $e = $this->mapException($e, 'BEGIN TRANSACTION');
            if (
                $e instanceof StatementException\ConnectionException
                && $this->options['reconnect']
            ) {
                $this->disconnect();
                try {
                    return $this->getPDO()->beginTransaction();
                } catch (Throwable $e) {
                    throw $this->mapException($e, 'BEGIN TRANSACTION');
                }
            }
        }
    }
    $this->createSavepoint($this->transactionLevel);
    return true;
}
```
вызов `$this->disconnect();` где вунтри
vendor/spiral/database/src/Driver/Driver.php:271
```php
public function disconnect(): void
{
    try {
        $this->queryCache = [];
        $this->pdo = null;
    } catch (Throwable $e) {
        // disconnect error
        if ($this->logger !== null) {
            $this->logger->error($e->getMessage());
        }
    }
    $this->transactionLevel = 0;
}
```
`$this->transactionLevel = 0;` - присваивается 0

**Comment by Hunternnm** [comment]
Move to https://github.com/spiral/database/issues/50
