### ISSUE TITLE
 Typed property must not be accessed before initialization

### ISSUE THREAD

**Issue by Anlamas** [cycle/orm#162]
Использую PHP 7.4
Обычные сущности для Many To Many.
Пытаюсь связать существующие записи.
Ругается на типизированное свойство в pivot entity при сохранении.
```Typed property App\CategoryContractor::$id must not be accessed before initialization```
```
/**
 * @Cycle\Entity(table="category_contractor")
 */
class CategoryContractor
{
    /**
     * @Cycle\Column(type="primary")
     */
    public int $id;
}
```

**Comment by wolfy-j** [comment]
Can you provide the ORM version, list of connected entities and full stack trace.

**Comment by Anlamas** [comment]
```
name     : cycle/orm
descrip. : PHP DataMapper ORM and Data Modelling Engine
keywords :
versions : * v1.3.3
```

```
<?php

namespace App;

use Cycle\Annotated\Annotation as Cycle;

/**
 * @Cycle\Entity()
 */
class Category
{
    /**
     * @Cycle\Column(type="primary")
     */
    protected int $id;

    public function getId(): int
    {
        return $this->id;
    }

    public function setId(int $id): Category
    {
        $this->id = $id;
        return $this;
    }
}
```

```
<?php

namespace App;

use Cycle\Annotated\Annotation as Cycle;

/**
 * @Cycle\Entity()
 */
class Contractor
{
    /**
     * @Cycle\Column(type="primary")
     */
    protected int $id;

    public function getId(): int
    {
        return $this->id;
    }

    public function setId(int $id): Contractor
    {
        $this->id = $id;
        return $this;
    }
}
```

```
<?php

namespace App;

use Cycle\Annotated\Annotation as Cycle;

/**
 * @Cycle\Entity(table="category_contractor")
 */
class CategoryContractor
{
    /**
     * @Cycle\Column(type="primary")
     */
    public int $id;
}
```

```
PHP Fatal error:  Uncaught Error: Typed property App\CategoryContractor::$id must not be accessed before initialization in /home/vagrant/code/demo/www/vendor/laminas/laminas-hydrator/src/ReflectionHydrator.php:41
Stack trace:
#0 /home/vagrant/code/demo/www/vendor/laminas/laminas-hydrator/src/ReflectionHydrator.php(41): ReflectionProperty->getValue()
#1 /home/vagrant/code/demo/www/vendor/cycle/orm/src/Mapper/Mapper.php(81): Laminas\Hydrator\ReflectionHydrator->extract()
#2 /home/vagrant/code/demo/www/vendor/cycle/orm/src/Mapper/Mapper.php(92): Cycle\ORM\Mapper\Mapper->extract()
#3 /home/vagrant/code/demo/www/vendor/cycle/orm/src/Mapper/DatabaseMapper.php(91): Cycle\ORM\Mapper\Mapper->fetchFields()
#4 /home/vagrant/code/demo/www/vendor/cycle/orm/src/CommandGenerator.php(33): Cycle\ORM\Mapper\DatabaseMapper->queueCreate()
#5 /home/vagrant/code/demo/www/vendor/cycle/orm/src/ORM.php(344): Cycle\ORM\CommandGenerator->generateStore()
#6 /home/vagrant/code/demo/www/vendor in /home/vagrant/code/demo/www/vendor/laminas/laminas-hydrator/src/ReflectionHydrator.php on line 41

Fatal error: Uncaught Error: Typed property App\CategoryContractor::$id must not be accessed before initialization in /home/vagrant/code/demo/www/vendor/laminas/laminas-hydrator/src/ReflectionHydrator.php:41
Stack trace:
#0 /home/vagrant/code/demo/www/vendor/laminas/laminas-hydrator/src/ReflectionHydrator.php(41): ReflectionProperty->getValue()
#1 /home/vagrant/code/demo/www/vendor/cycle/orm/src/Mapper/Mapper.php(81): Laminas\Hydrator\ReflectionHydrator->extract()
#2 /home/vagrant/code/demo/www/vendor/cycle/orm/src/Mapper/Mapper.php(92): Cycle\ORM\Mapper\Mapper->extract()
#3 /home/vagrant/code/demo/www/vendor/cycle/orm/src/Mapper/DatabaseMapper.php(91): Cycle\ORM\Mapper\Mapper->fetchFields()
#4 /home/vagrant/code/demo/www/vendor/cycle/orm/src/CommandGenerator.php(33): Cycle\ORM\Mapper\DatabaseMapper->queueCreate()
#5 /home/vagrant/code/demo/www/vendor/cycle/orm/src/ORM.php(344): Cycle\ORM\CommandGenerator->generateStore()
#6 /home/vagrant/code/demo/www/vendor in /home/vagrant/code/demo/www/vendor/laminas/laminas-hydrator/src/ReflectionHydrator.php on line 41
```

**Comment by Anlamas** [comment]
What i'm trying to do
```
foreach ($contractors as $contractor) {
    foreach ($categories as $category) {
            $contractor->getCategories()->add($category);
            $tr->persist($contractor);
        }
}

$tr->run();
```
As a temporal solution i removed type `int` from property `$id`

**Comment by roxblnfk** [comment]
> As a temporal solution i removed type `int` from property `$id`

Как временное решение можно также определять поле как `?int $id = null`. В какой-то степени это даже логично.

**Comment by wolfy-j** [comment]
Если I’d генерируясь базой то он должен быть nullable. По другому ОРМ просто не знает где взять данные.

**Comment by adamdyson** [comment]
```
/**
 * @Column(type = "primary")
 */
protected ?int $id = null;
```

**Comment by wolfy-j** [comment]
@roxblnfk

**Comment by roxblnfk** [comment]
@wolfy-j what?
