### ISSUE TITLE
🐛  Exception on persist entity with BelongsTo and cascade=false: Argument #2 ($rTuple) must be of type Cycle\\ORM\\Transaction\\Tuple, null given

### ISSUE THREAD

**Issue by vokomarov** [cycle/orm#335]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!

Getting error when trying to save entity with BelongTo relation using `cascade=false`.
```
Cycle\\ORM\\Relation\\BelongsTo::shouldPull(): Argument #2 ($rTuple) must be of type Cycle\\ORM\\Transaction\\Tuple, null given, called in /root/vendor/cycle/orm/src/Relation/BelongsTo.php on line 100
```

Code that triggering error
```php
$user = $container->get(\App\Repository\UserRepository::class)->find(1);
$tr = $container->get(\Cycle\ORM\EntityManagerInterface::class);
$tr->persist($user);
$tr->run();
```

Entity
```php
use Cycle\Annotated\Annotation as Cycle;

#[Cycle\Entity]
class User {
    #[Cycle\Relation\BelongsTo(target: Currency::class, innerKey: 'default_currency_code', cascade: false, load: 'eager')]
    private Currency $defaultCurrency;
}
```

<details>
  <summary>ORM Schema:</summary>
 
  ```javascript
  [forgotPasswordRequest] :: default.forgot_password_requests
       Entity: App\Database\ForgotPasswordRequest
       Mapper: Cycle\ORM\Mapper\Mapper
   Repository: App\Repository\ForgotPasswordRequestRepository
  Primary key: email
       Fields:
               (property -> db.field -> typecast)
               email -> email
               code -> code
               createdAt -> created_at -> datetime
    Relations: not defined

[wallet] :: default.wallets
       Entity: App\Database\Wallet
       Mapper: Cycle\ORM\Mapper\Mapper
   Repository: App\Repository\WalletRepository
  Primary key: id
       Fields:
               (property -> db.field -> typecast)
               id -> id -> int
               name -> name
               slug -> slug
               totalAmount -> total_amount -> float
               isActive -> is_active -> bool
               isArchived -> is_archived -> bool
               isPublic -> is_public -> bool
               defaultCurrencyCode -> default_currency_code
               createdAt -> created_at -> datetime
               updatedAt -> updated_at -> datetime
    Listeners:
             Cycle\ORM\Entity\Behavior\Listener\CreatedAt
              - field : createdAt
             Cycle\ORM\Entity\Behavior\Listener\UpdatedAt
              - field : updatedAt
              - nullable : false
    Relations:
     wallet->defaultCurrency belongs to currency, eager loading, not cascaded
       not null wallet.defaultCurrencyCode <==> currency.code
     wallet->charges has many charge, lazy loading, cascaded
       not null wallet.id <==> charge.wallet_id
     wallet->users many to many user, lazy loading, cascaded
       not null wallet.id <= userWallet.wallet_id | userWallet.user_id => user.id

[charge] :: default.charges
       Entity: App\Database\Charge
       Mapper: Cycle\ORM\Mapper\Mapper
   Repository: App\Repository\ChargeRepository
  Primary key: id
       Fields:
               (property -> db.field -> typecast)
               id -> id
               walletId -> wallet_id -> int
               userId -> user_id -> int
               type -> type
               amount -> amount -> float
               title -> title
               currencyExchangeId -> currency_exchange_id -> int
               description -> description
               createdAt -> created_at -> datetime
               updatedAt -> updated_at -> datetime
               wallet_id -> wallet_id -> int
               user_id -> user_id -> int
               uuid -> uuid -> Ramsey\Uuid\Uuid::fromString
     Typecast: Cycle\ORM\Parser\Typecast
    Listeners:
             Cycle\ORM\Entity\Behavior\Uuid\Listener\Uuid4
              - field : uuid
             Cycle\ORM\Entity\Behavior\Listener\CreatedAt
              - field : createdAt
             Cycle\ORM\Entity\Behavior\Listener\UpdatedAt
              - field : updatedAt
              - nullable : false
    Relations:
     charge->wallet belongs to wallet, lazy loading, cascaded
       not null charge.walletId <==> wallet.id
     charge->user belongs to user, lazy loading, cascaded
       not null charge.user_id <==> user.id
     charge->currencyExchange belongs to currencyExchange, lazy loading, cascaded
       nullable charge.currencyExchangeId <==> currencyExchange.id

[userWallet] :: default.user_wallets
       Entity: App\Database\UserWallet
       Mapper: Cycle\ORM\Mapper\Mapper
   Repository: Cycle\ORM\Select\Repository
  Primary key: id
       Fields:
               (property -> db.field -> typecast)
               id -> id -> int
               wallet_id -> wallet_id -> int
               user_id -> user_id -> int
    Relations: not defined

[user] :: default.users
       Entity: App\Database\User
       Mapper: Cycle\ORM\Mapper\Mapper
   Repository: App\Repository\UserRepository
  Primary key: id
       Fields:
               (property -> db.field -> typecast)
               id -> id -> int
               name -> name
               lastName -> last_name
               nickName -> nick_name
               email -> email
               isEmailConfirmed -> is_email_confirmed -> bool
               photo -> photo
               defaultCurrencyCode -> default_currency_code
               password -> password
               createdAt -> created_at -> datetime
               updatedAt -> updated_at -> datetime
    Listeners:
             Cycle\ORM\Entity\Behavior\Listener\CreatedAt
              - field : createdAt
             Cycle\ORM\Entity\Behavior\Listener\UpdatedAt
              - field : updatedAt
              - nullable : false
    Relations:
     user->defaultCurrency belongs to currency, eager loading, not cascaded
       not null user.defaultCurrencyCode <==> currency.code
     user->wallets many to many wallet, lazy loading, cascaded
       not null user.id <= userWallet.user_id | userWallet.wallet_id => wallet.id

[emailConfirmation] :: default.email_confirmations
       Entity: App\Database\EmailConfirmation
       Mapper: Cycle\ORM\Mapper\Mapper
   Repository: App\Repository\EmailConfirmationRepository
  Primary key: email
       Fields:
               (property -> db.field -> typecast)
               email -> email
               token -> token
               createdAt -> created_at -> datetime
    Relations: not defined

[currencyExchange] :: default.currency_exchanges
       Entity: App\Database\CurrencyExchange
       Mapper: Cycle\ORM\Mapper\Mapper
   Repository: App\Repository\CurrencyExchangeRepository
  Primary key: id
       Fields:
               (property -> db.field -> typecast)
               id -> id -> int
               srcCurrencyCode -> src_currency_code
               srcAmount -> src_amount -> float
               rate -> rate -> float
               dstCurrencyCode -> dst_currency_code
               dstAmount -> dst_amount -> float
               createdAt -> created_at -> datetime
               updatedAt -> updated_at -> datetime
    Listeners:
             Cycle\ORM\Entity\Behavior\Listener\CreatedAt
              - field : createdAt
             Cycle\ORM\Entity\Behavior\Listener\UpdatedAt
              - field : updatedAt
              - nullable : false
    Relations:
     currencyExchange->srcCurrency belongs to currency, lazy loading, cascaded
       not null currencyExchange.srcCurrencyCode <==> currency.code
     currencyExchange->dstCurrency belongs to currency, lazy loading, cascaded
       not null currencyExchange.dstCurrencyCode <==> currency.code

[currency] :: default.currencies
       Entity: App\Database\Currency
       Mapper: Cycle\ORM\Mapper\Mapper
   Repository: App\Repository\CurrencyRepository
  Primary key: code
       Fields:
               (property -> db.field -> typecast)
               code -> code
               name -> name
               char -> char
               rate -> rate -> float
               updatedAt -> updated_at -> datetime
    Relations: not defined

  ```
  
</details>

### Version

```shell
ORM 2.1.0
Spiral 2.11.0
PHP 8.1
```

**Comment by roxblnfk** [comment]
I can't reproduce this case i tests. Could you help me?

I need ORM Schema as array and, if it possible, entities with fields.

You can do an example (new test case) manually if you want. For example: https://github.com/cycle/orm/tree/2.x/tests/ORM/Functional/Driver/Common/Integration

**Comment by vokomarov** [comment]
Hi @roxblnfk , thank you for looking into that. I made an complete example which you can try.

`test.php`:
```php
<?php

require_once 'vendor/autoload.php';

use Cycle\Annotated\Annotation as Cycle;
use Cycle\Database;
use Cycle\Database\Config;
use Cycle\ORM;
use Cycle\ORM\EntityManager;
use Cycle\ORM\Schema;
use Cycle\ORM\Mapper\Mapper;

#[Cycle\Entity]
class User {
    #[Cycle\Column('primary')]
    public int|null $id = null;

    #[Cycle\Relation\BelongsTo(target: Currency::class, innerKey: 'default_currency_code', cascade: false, load: 'lazy')]
    private Currency $defaultCurrency;

    public function setDefaultCurrency(Currency $currency)
    {
        $this->defaultCurrency = $currency;
    }
}

#[Cycle\Entity]
class Currency {
    #[Cycle\Column(type: 'string(3)', primary: true)]
    public string|null $code = null;
}

$dbal = new Database\DatabaseManager(
    new Config\DatabaseConfig([
        'default' => 'default',
        'databases' => [
            'default' => ['connection' => 'sqlite']
        ],
        'connections' => [
            'sqlite' => new Config\SQLiteDriverConfig(
                connection: new Config\SQLite\MemoryConnectionConfig(),
                queryCache: true,
            ),
        ]
    ])
);

$orm = new ORM\ORM(new ORM\Factory($dbal), new Schema([
    'user' => [
        Schema::MAPPER => Mapper::class,
        Schema::ENTITY => User::class,
        Schema::DATABASE => 'default',
        Schema::TABLE => 'users',
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'defaultCurrencyCode' => 'default_currency_code',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
        ],
        Schema::RELATIONS => [
            'defaultCurrency' => [
                0 => 12,
                1 => 'currency',
                3 => 11,
                2 => [
                    30 => false,
                    31 => false,
                    33 => [
                        0 => 'defaultCurrencyCode',
                    ],
                    32 => [
                        0 => 'code',
                    ],
                ],
            ],
        ],
    ],
    'currency' => [
        Schema::ENTITY => Currency::class,
        Schema::MAPPER => Mapper::class,
        Schema::DATABASE => 'default',
        Schema::TABLE => 'currencies',
        Schema::PRIMARY_KEY => [
            0 => 'code',
        ],
        Schema::COLUMNS => [
            'code' => 'code'
        ],
        Schema::RELATIONS => [],
    ],
]));

$currency = new Currency();
$currency->code = 'USD';

$user = new User();
$user->setDefaultCurrency($currency);

(new EntityManager($orm))->persist($user)->run();
```

Assuming you have `composer.json`:
```json
{
  "name": "test/test",
  "type": "project",
  "require": {
    "php": ">=8.1",
    "ext-mbstring": "*",
    "ext-openssl": "*",
    "ext-pdo": "*",
    "aws/aws-sdk-php": "^3.190",
    "cycle/entity-behavior": "^1.1",
    "cycle/entity-behavior-uuid": "^1.0",
    "doctrine/collections": "^1.6",
    "firebase/php-jwt": "^5.2",
    "illuminate/collections": "^9.8",
    "kreait/firebase-php": "^5.0",
    "laminas/laminas-diactoros": "^2.6",
    "lcobucci/jwt": "4.1.5",
    "ramsey/uuid": "^4.2",
    "spiral/cycle-bridge": "^v1.2",
    "spiral/framework": "^2.11",
    "spiral/nyholm-bridge": "^1.1",
    "spiral/roadrunner-bridge": "^1.0",
    "swiftmailer/swiftmailer": "^6.2",
    "voku/portable-utf8": "^5.4"
  },
  "require-dev": {
    "phpunit/phpunit": "^9.5",
    "squizlabs/php_codesniffer": "3.*",
    "spiral/testing": "^1.1",
    "vimeo/psalm": "^4.9"
  },
  "scripts": {
    "post-create-project-cmd": [
      "php -r \"copy('.env.sample', '.env');\"",
      "php app.php encrypt:key -m .env",
      "php app.php configure -vv",
      "spiral get-binary"
    ],
    "checks": [
      "./vendor/bin/phpunit",
      "./vendor/bin/phpcs -p -n --standard=PSR12 --colors --report=code ./app/src",
      "./vendor/bin/psalm --php-version=8.0 --show-info=true --no-cache"
    ],
    "phpunit": [
      "./vendor/bin/phpunit"
    ],
    "phpcs": [
      "./vendor/bin/phpcs -p -n --standard=PSR12 --colors --report=code ./app/src"
    ],
    "psalm": [
      "./vendor/bin/psalm --php-version=8.1 --show-info=true --no-cache"
    ]
  },
  "autoload": {
    "files": [
      "app/helpers/str.php"
    ],
    "psr-4": {
      "App\\": "app/src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  },
  "extra": {
    "publish-cmd": "php app.php publish",
    "branch-alias": {
      "dev-master": "1.4.x-dev"
    }
  },
  "config": {
    "sort-packages": true,
    "allow-plugins": {
      "spiral/composer-publish-plugin": true
    }
  },
  "minimum-stability": "dev",
  "prefer-stable": true
}

```

And then simply 
```shell
$ php test.php
```

Which gives for me:
```
 php test.php
PHP Fatal error:  Uncaught TypeError: Cycle\ORM\Relation\BelongsTo::shouldPull(): Argument #2 ($rTuple) must be of type Cycle\ORM\Transaction\Tuple, null given, called in /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Relation/BelongsTo.php on line 100 and defined in /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Relation/BelongsTo.php:107
Stack trace:
#0 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Relation/BelongsTo.php(100): Cycle\ORM\Relation\BelongsTo->shouldPull(Object(Cycle\ORM\Transaction\Tuple), NULL)
#1 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Transaction/UnitOfWork.php(250): Cycle\ORM\Relation\BelongsTo->queue(Object(Cycle\ORM\Transaction\Pool), Object(Cycle\ORM\Transaction\Tuple))
#2 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Transaction/UnitOfWork.php(362): Cycle\ORM\Transaction\UnitOfWork->resolveMasterRelations(Object(Cycle\ORM\Transaction\Tuple), Object(Cycle\ORM\RelationMap))
#3 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Transaction/UnitOfWork.php(218): Cycle\ORM\Transaction\UnitOfWork->resolveRelations(Object(Cycle\ORM\Transaction\Tuple))
#4 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Transaction/UnitOfWork.php(96): Cycle\ORM\Transaction\UnitOfWork->walkPool()
#5 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/EntityManager.php(47): Cycle\ORM\Transaction\UnitOfWork->run()
#6 /Users/vovan/projects/cash-track/api/test.php(101): Cycle\ORM\EntityManager->run()
#7 {main}
  thrown in /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Relation/BelongsTo.php on line 107

Fatal error: Uncaught TypeError: Cycle\ORM\Relation\BelongsTo::shouldPull(): Argument #2 ($rTuple) must be of type Cycle\ORM\Transaction\Tuple, null given, called in /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Relation/BelongsTo.php on line 100 and defined in /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Relation/BelongsTo.php:107
Stack trace:
#0 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Relation/BelongsTo.php(100): Cycle\ORM\Relation\BelongsTo->shouldPull(Object(Cycle\ORM\Transaction\Tuple), NULL)
#1 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Transaction/UnitOfWork.php(250): Cycle\ORM\Relation\BelongsTo->queue(Object(Cycle\ORM\Transaction\Pool), Object(Cycle\ORM\Transaction\Tuple))
#2 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Transaction/UnitOfWork.php(362): Cycle\ORM\Transaction\UnitOfWork->resolveMasterRelations(Object(Cycle\ORM\Transaction\Tuple), Object(Cycle\ORM\RelationMap))
#3 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Transaction/UnitOfWork.php(218): Cycle\ORM\Transaction\UnitOfWork->resolveRelations(Object(Cycle\ORM\Transaction\Tuple))
#4 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Transaction/UnitOfWork.php(96): Cycle\ORM\Transaction\UnitOfWork->walkPool()
#5 /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/EntityManager.php(47): Cycle\ORM\Transaction\UnitOfWork->run()
#6 /Users/vovan/projects/cash-track/api/test.php(101): Cycle\ORM\EntityManager->run()
#7 {main}
  thrown in /Users/vovan/projects/cash-track/api/vendor/cycle/orm/src/Relation/BelongsTo.php on line 107

```
